version: '3'

services:
    db:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        volumes:
            - ./db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=castel
            - POSTGRES_DB=django-postgres
        networks:
            - django-test
    redis:
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_PORT_NUMBER=6379
        ports:
            - 6379:6379
        networks:
            - django-test
    django-server:
        image: django-server
        build: .
        environment:
            DB_NAME: django-postgres
            DB_USER: castel
            DB_PASSWORD: 1234
            DB_HOST: db
            DB_PORT: 5432
        networks:
            - django-test
        ports:
            - 8000:8000

networks:
    django-test:
        name: django-test
